"""create_news_table

Revision ID: 1f43557e4949
Revises: 
Create Date: 2025-11-22 13:58:41.314883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f43557e4949'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=False),
    sa.Column('proposition_number', sa.String(length=20), nullable=False),
    sa.Column('proposition_id', sa.Integer(), nullable=False),
    sa.Column('presentation_date', sa.Date(), nullable=False),
    sa.Column('uf_author', sa.String(length=2), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('news_type', sa.String(length=10), nullable=False),
    sa.Column('original_ementa', sa.Text(), nullable=False),
    sa.Column('pdf_storage_url', sa.String(length=500), nullable=False),
    sa.Column('original_pdf_url', sa.String(length=500), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('published_to_social', sa.Boolean(), nullable=False),
    sa.Column('social_publish_date', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_engagement_score'), 'news', ['engagement_score'], unique=False)
    op.create_index(op.f('ix_news_news_type'), 'news', ['news_type'], unique=False)
    op.create_index(op.f('ix_news_proposition_id'), 'news', ['proposition_id'], unique=True)
    op.create_index(op.f('ix_news_proposition_number'), 'news', ['proposition_number'], unique=False)
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    op.create_index(op.f('ix_news_uf_author'), 'news', ['uf_author'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_uf_author'), table_name='news')
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_index(op.f('ix_news_proposition_number'), table_name='news')
    op.drop_index(op.f('ix_news_proposition_id'), table_name='news')
    op.drop_index(op.f('ix_news_news_type'), table_name='news')
    op.drop_index(op.f('ix_news_engagement_score'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
